version: 1.0.0.{build}

configuration: Debug

before_build:
  - nuget restore "./src/SurplusCalculator.sln"

test:
  assemblies:
    - '**\*.Tests.dll'
    
artifacts:  
- path: '**\*.nupkg'
  name: NuGet