version: 1.0.0.{build}

configuration: Release(Setup)

before_build:
  - nuget restore "./src/SurplusCalculator.sln"

test:
  assemblies:
    - '**\*.Tests.dll'
    
artifacts:  
  - path: '**\*.msi'
