version: 1.2.0.{build}

platform: Any CPU
configuration: Release(Setup)

skip_tags: true

before_build:
  - nuget restore "./src/SurplusCalculator.sln"

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
test:
  assemblies:
    - '**\*.Tests.dll'
    
artifacts:
  - path: '**\*.msi'
